home->+WIP: 
WIP->+customerData: 
customerData-->-WIP:
WIP->+accountData: 
accountData-->-WIP:
WIP->+activityData:
activityData-->-WIP:
WIP-->+commitWIP:
commitWIP->-home:
WIP-->+cancelWIP:
cancelWIP->-home:
